### ISSUE TITLE
Emacs 29 is required

### ISSUE THREAD

**Issue by WorldsEndless** [alphapapa/listen.el#14]
I cannot run `M-x listen`. I get the error 

```
condition-case: Cannot open load file: No such file or directory, vtable
```

GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)

**Comment by WorldsEndless** [comment]
I'm guessing that there is a Emacs 29 dependency, where vtable is included, reading https://lars.ingebrigtsen.no/2022/04/13/more-vtable-fun/

**Comment by alphapapa** [comment]
Yes, I neglected to put that in the headers.  Thanks for mentioning it.

**Comment by alphapapa** [comment]
Well, no, it's already there:  https://github.com/alphapapa/listen.el/blob/2572ecbc1821af2a0b50ab7c87cac8de8462c89c/listen.el#L8

If you install it with `package-install`, it won't let you install it on Emacs 28.

**Comment by alphapapa** [comment]
Yes.  Is the "package-requires" header not enough?

**Comment by WorldsEndless** [comment]
is that in the code somewhere? I base most of my "getting started" off what I see on the front page, from the readme

**Comment by alphapapa** [comment]
> is that in the code somewhere?

Sorry, I don't understand what you mean.   Yes, the package-requires header is in the source code, at the top of the file.

**Comment by WorldsEndless** [comment]
I guess I should get in the habit of reading the code more often; I don't usually do it as part of a "try it out" effort

**Comment by alphapapa** [comment]
I will add it to the readme.  I forget how many people still use Emacs 28.  I was expecting that ones who did would install it with `package-install` and have the version checked that way.
