### ISSUE TITLE
It is not possible to change/redefine keybindings

### ISSUE THREAD

**Issue by Heathcliff77** [alphapapa/listen.el#24]
As established in this discussion: https://github.com/alphapapa/listen.el/discussions/22 it is currently impossible to change/redefine `listen` keybindings to your own liking. Keybindings are hardcoded into source code.

(Side note: The README states that `listen.el` aims to "_be easily extended and customized_" . So I guess developers agree on that this should be possible (in some coming version of listen.el) )

**Comment by alphapapa** [comment]
See https://github.com/alphapapa/listen.el/discussions/22
