### ISSUE TITLE
doesn't install on emacs 30

### ISSUE THREAD

**Issue by tvraman** [alphapapa/listen.el#6]
Invalid read syntax: #

**Comment by alphapapa** [comment]
I don't have Emacs 30, so I can't try to reproduce this problem.  As well, that error could be coming from anywhere.  And since the package works fine on Emacs 29, it must be a problem with Emacs 30 (or your configuration).  So please report it to Emacs.

**Comment by tvraman** [comment]
I'll attach a backtrace in case it is useful.

Debugger entered--Lisp error: (invalid-read-syntax "#")
  (signal invalid-read-syntax ("#"))
  (async-handle-result (lambda (x) (setq package-alist (pop x) package-selected-packages (pop x) package-archive-contents (pop x)) (when (spinner-p paradox--spinner) (spinner-stop paradox--spinner) (setq paradox--spinner nil)) (setq paradox--executing nil) (run-hook-with-args 'paradox-after-execute-functions (pop x)) (paradox--post-execute-star-unstar 'nil (paradox--repo-alist))) (async-signal (invalid-read-syntax "#")) #<buffer *emacs*>)
  (async-when-done #<process emacs> "finished\n")

--

**Comment by tvraman** [comment]
Appears to be an error due to package paradox, restarting emacs, and running list-packages succeeds
